### PR TITLE
Different Events cookie name for multiple windows/tabs

### LINKED ISSUE #16: Post same event multiple times if you have more than one window/tab.
If you have a click event trigger ahoy.track, and that click opens a new window or tab, it will post the event twice. I think is because when window/tab loads check for eventQueue and the event is still on eventQueue.
I think the solution is to set the cookie name to ahoy_events_TIMESTAMP. So every window/tab will work on a different cookie.

I found it using ctrl + click on a anchor tag using click event.

### PR DESCRIPTION
**Pull request by rddm2bb**
Fix #16

### CODE REVIEW

**Comment by ankane** [comment]
Hey @rddm2bb, thanks for the PR 👍  Any reason Ahoy couldn't use just session storage for the events queue instead of cookies?

**Comment by rddm2bb** [comment]
@ankane no, you can use sessionStorage instead of cookies, that way you don't need to set a different name for each tab/window. The only problem I see is if you close the window/tab before empty the queue beacause you will not receive the data (cookies with different name, have the same problem).
It's analytics, for me isn't a problem.

**Comment by rddm2bb** [comment]
@ankane SessionStorage is not scoped by domain, so if you move, in the same session, to another site that use ahoy and you don't have your eventQueue empty, you will submit events that don't belong to that site.

**Comment by ankane** [comment]
> SessionStorage is not scoped by domain

@rddm2bb I don't think that's true. Where are you seeing that?

**Pull request closed without merging**
