### PR TITLE
Added cross origin functionality and the ability to pass in request headers

### PR DESCRIPTION
**Pull request by crwang**
This helps connect to an API that is not served up on the same domain.

### CODE REVIEW

**Comment by Uladzimiro** [comment]
Hello, @ankane ! Any chance we can merge this one? We are using npm to install ahoy.js . However, we want to send visits and events tracking requests to a different subdomain and there are no relevant ahoy cookies there. So, we want to use alternative approach - use Headers to get `visitor_id` and `visit_id`.

I've added another PR to @crwang 's fork - which already rebased against origin/master.

Please, help us to merge it as fast as possible. Thanks

**Comment by madisvain** [comment]
This would be a great feature to have for ahoy.js

**Comment by ankane** [comment]
Sorry for the (very) slow response.  I think it makes sense to pass the visit and visitors tokens in the request (rather than count on cookies - or even headers).  Why don't we add a `visit_token` and `visitor_token` to the request body?

**Comment by ankane** [comment]
With d88cba1c55f86b9686be0c4aaeed1d4f7740a935, this should no longer be needed. Let me know if it doesn't solve it.

**Pull request closed without merging**
