### PR TITLE
chore: create option to configure visitDuration and visitorDuration 

### LINKED ISSUE #49: Create option to configure visitTtl and visitorTtl
Hello, our team uses your lib and we had some difficulties with the default value of `visitTtl` and `visitorTtl`, mainly because of `visitTtl`.

Basically, our session token expires in thirty days, while the `ahoy_visit` cookie expires in four hours. After four hours, the `ahoy_visit` cookie is renewed and our backend loses control of the events because a new `visit_token` is created.

Our suggestion is to keep the default valves, but create a option to configure these values on the `configure` function.

I will send a PR with the code change and, if it makes sense, let me know and I will update the documentation as well.

### PR DESCRIPTION
**Pull request by thejullius**
fixes #49 

add a option to configure visitDuration and visitorDuration 

```  
ahoy.configure({
    ...
    visitDuration: 30 * 24 * 60, // 30 days
    visitorDuration: 30 * 24 * 60 // 30 days
  })

### CODE REVIEW

**Comment by ankane** [comment]
Thanks @thejullius! Makes sense to me. Can we rename to `visitDuration` and `visitorDuration` to match the Ruby library?

**Comment by thejullius** [comment]
Of course, I also updated the README file :)

**Comment by agustin** [comment]
Hi @ankane, hope you're doing well! just wondering if there is an estimated date for this PR to be merge? thanks a lot for all the effort and work into all this libs and gems :)!

**Comment by ankane** [comment]
Thanks @thejullius!

**Pull request merged**
