### PR TITLE
Fix caching issues when trying to get DOM element's data-section attribute value

### PR DESCRIPTION
**Pull request by pazaricha**
### What I did
Instead of using jQuery's `.data` function, use the `.attr` function to prevent caching issue with elements that their data-section is changed dynamically.
Also bumped the version number.

#### How to reproduce the issue this solves:
1. Set data-section on any DOM element to some value. 
2. Click on it once.
3. Change it's data-section value to something else. 
4. Click on it again.
5. You will see that the second data-section you are getting in the event is the **old** data-section.

I already use this and it works perfectly.

### CODE REVIEW

**Comment by pazaricha** [comment]
@ankane Let me know if there is anything I need to change here. Thanks for creating such an awesome plugin :)

**Comment by ankane** [comment]
Hey @pazaricha, thanks for the PR 👍  Happy to merge if you revert the version bump.

**Comment by pazaricha** [comment]
@ankane - DONE :) also did on the the PR here: https://github.com/ankane/ahoy/pull/308

**Comment by ankane** [comment]
Looks good, thanks @pazaricha 👍

**Pull request merged**
