### PR TITLE
Extend cookie expiration for active visits

### PR DESCRIPTION
**Pull request by dnswus**
Expiration of `ahoy_visit` cookie should be extended if the visitor is
actively visiting other pages within the visitTtl.

### CODE REVIEW

**Comment by dnswus** [comment]
Hey @ankane, do you think this PR makes sense? We have implemented ahoy in a project that is using a separate domain for ahoy backend. And because of the cookie restriction, the `ahoy_visit` cookie is not extended by the ahoy backend. That's why we extend the expiration in the front end (which is what this repo is for).

**Comment by ankane** [comment]
Hey @dnswus, sorry I'm just getting to this now. Agree this makes sense. Happy to accept another PR, as it looks like there are now merge conflicts.

**Comment by dnswus** [comment]
@ankane resolved conflicts.

**Comment by ankane** [comment]
Thanks Dennis. I just realized we'll need to find a way to respect the `Ahoy.visit_duration` option of the [Ahoy gem](https://github.com/ankane/ahoy) before merging.

**Comment by ankane** [comment]
Hey @dnswus, the server now handles TTL for visits, so this should no longer be needed.

**Pull request closed without merging**
