### PR TITLE
add value to eventProperties

### PR DESCRIPTION
**Pull request by mohamedaitbella**
adding value to  eventProperties is exest

### CODE REVIEW

**Comment by ankane** [comment]
Hey @mohamedaitbella, can you explain this more?

**Comment by mohamedaitbella** [comment]
when tracking change on text field i could not have the value  of the text field so i  added this line  so i can have the value on /ahoy/events

**Comment by ankane** [comment]
Hey @mohamedaitbella, I think this will lead to Ahoy accidentally storing sensitive information. Due to that, I don’t think it makes sense to merge. Regardless, thanks for submitting it

**Comment by mohamedaitbella** [comment]
oh, I totally  get your point   thanks for fast replay

**Pull request closed without merging**
